services:
  ollama:
    container_name: ollama_node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ollama:11434"]
      interval: 30s
      timeout: 10s
      retries: 3
    build: 
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 4G
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  node_app:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - NODE_ENV=production

volumes:
  ollama_data: